#!/bin/bash

###########################################
## Simple settings manager for instantOS ##
###########################################

sq() {
    sqlite3 ~/.config/instantos/settings.db "$1"
}

case "$1" in
-b) # 1 or 0 to exit code
    shift
    BINARY=True
    ;;
-h)
    echo "usage:"
    echo "get setting: iconf setting"
    echo "set setting: iconf setting value"
    echo ""
    exit
    ;;
-d)
    # delete an option
    if [ -n "$2" ]; then
        sq 'DELETE * FROM settings WHERE setting='"$2"
    fi
    ;;
-i)
    # use indicator files
    [ -z "$2" ] && exit 1
    if [ -n "$3" ]; then
        if [ "$3" = "0" ]; then
            if [ -e ~/.config/iconf/"$2" ]; then
                rm ~/.config/iconf/"$2"
            fi
        else
            if ! [ -e ~/.config/iconf ]; then
                mkdir -p ~/.config/iconf
            fi
            if ! [ -e ~/.config/iconf/"$2" ]; then
                touch ~/.config/iconf/"$2"
            fi
        fi
        exit 0
    else
        [ -e ~/.config/iconf/"$2" ] && exit 0
    fi
    exit 1
    ;;

-f)
    # store in files instead of sqlite
    shift 1
    if [ -z "$2" ]; then
        if [ -e ~/.config/instantconf/"$1" ]; then
            cat ~/.config/instantconf/"$1"
        else
            exit 1
        fi
    else
        echo "$2" >~/.config/instantconf/"$1"
    fi
    ;;
all)
    sq 'SELECT * FROM SETTINGS'
    exit
    ;;
esac

# initialize new settings
if ! [ -e ~/.config/instantos/settings.db ]; then
    mkdir -p ~/.config/instantos
    sq 'CREATE TABLE "settings" ("setting" TEXT constraint_name PRIMARY KEY, "value" TEXT);'
    # default settings
    sq 'INSERT INTO settings (setting, value) VALUES ("welcome", "1")' # startup welcome app
fi

if [ -n "$2" ]; then
    sq 'REPLACE INTO settings (setting, value) VALUES ("'"$1"'", "'"$2"'")'
else
    if [ -z "$BINARY" ]; then
        # setting:default returns something even if there's no entry in the database
        if [[ "$1" =~ ":" ]]; then
            SETTING="${1%:*}"
            DEFAULT="${1#*:}"
        else
            SETTING="$1"
        fi

        VALUE=$(sq 'SELECT value FROM settings WHERE setting="'"$SETTING"'"')
        if [ -z "$VALUE" ]; then
            if [ -z "$DEFAULT" ]; then
                exit 1
            else
                echo "$DEFAULT"
            fi
        else
            echo "$VALUE"
        fi
    else
        VALUE=$(sq 'SELECT value FROM settings WHERE setting="'"$1"'"')
        if [ "$VALUE" = "1" ]; then
            exit 0
        else
            exit 1
        fi
    fi
fi
